spring:
  profiles:
    active: dev
    

---
#开发环境

#服务器相关配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml    
#spring配置
spring:
  profiles: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  aop:
    auto: true
  #数据源
  datasource:
    druid:
      filters: mergeStat,wall
      initial-size: 5
      max-active: 50
      min-idle: 5
      max-wait: 6000
      validation-query: SELECT 'x'
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
      dubbo:
        url: jdbc:mysql://localhost:3306/dubbo?characterEncoding=utf8&serverTimezone=CTT
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver

#dubbo配置        
dubbo: 
  registry: 
    address: zookeeper://localhost:2181
  protocol:
    address: localhost
    port: 38080